In [19]:
import torch
torch.cuda.device_count()

1

In [20]:
X = torch.ones(2, 3, device='cuda:0').to(torch.float32)
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [21]:
y = torch.tensor([2,3,5]).to(torch.float32)
y

tensor([2., 3., 5.])

In [22]:
y = y.to('cuda')

In [25]:
torch.matmul(X,y)

tensor([10., 10.], device='cuda:0')